version: '3.8'

# =============================================================================
# Portainer CE Stack for Docker Swarm
# =============================================================================
# Deploy with: docker stack deploy -c portainer-stack.yml portainer
# Access UI at: https://<any-manager-ip>:9443
#
# Architecture:
# - Portainer Server: Runs on any manager node (CephFS shared storage)
# - Portainer Agent: Global mode (runs on ALL nodes)
#
# Storage: /mnt/cephfs/portainer (CephFS, replicated 3x across pve01-03)
# BoltDB persists across node failovers — Portainer follows Swarm scheduling.
# =============================================================================

services:
  # ===========================================================================
  # Portainer Agent - Runs on EVERY node in the cluster (Global Mode)
  # ===========================================================================
  # The agent provides Docker API access from each node to the central server.
  # Memory footprint: ~20MB per node
  agent:
    image: portainer/agent:2.21.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M

  # ===========================================================================
  # Portainer Server - Any Swarm manager (CephFS shared storage)
  # ===========================================================================
  # Central management server with web UI.
  # BoltDB stored on CephFS — available on all 3 infra nodes simultaneously.
  portainer:
    image: portainer/portainer-ce:2.21.5
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"   # HTTPS Web UI
      - "9000:9000"   # HTTP Web UI (optional, can be removed for security)
      - "8000:8000"   # Edge Agent Tunnel (for remote/edge deployments)
    volumes:
      - /mnt/cephfs/portainer:/data   # CephFS bind mount (replicated 3x)
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager        # Any manager (CephFS available on all)
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
      restart_policy:
        condition: any
        delay: 10s
        window: 120s

networks:
  agent_network:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"  # Encrypt overlay network traffic
