version: '3.8'

# Swarmpit Docker Swarm Management Stack
# Deploy with: docker stack deploy -c swarmpit-stack.yml swarmpit
# Access UI at: http://<any-swarm-node>:888

services:
  # CouchDB Database for Swarmpit
  db:
    image: couchdb:3.3
    volumes:
      - db_data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=SwarmPit2026SecurePass
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # InfluxDB for metrics (must use 1.8, not 2.x!)
  influxdb:
    image: influxdb:1.8
    volumes:
      - influx_data:/var/lib/influxdb
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Swarmpit Agent - runs on all nodes
  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

  # Swarmpit App - Web UI
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://admin:SwarmPit2026SecurePass@db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "888:8080"
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db_data:
  influx_data:
